### PR TITLE
A number of fixes and improvements

### PR DESCRIPTION
**Pull request by montoner0**
#19

### CODE REVIEW

**Comment by Jamminroot** [comment]
Sorry for a delay, want to run through the code and check the built artifact first

**Comment by Jamminroot** [comment]
It's all great, except for the UACHelper - I don't really like the concept of using nugets in this specific app, as I try to keep it a single artifact, without DLLs - this is why I ripped some of the code and made it "embedded" to sources.

Can you either remove it, or embed relevant parts? Similar to what I did with PropVar, PropertyKey and others.

**Comment by montoner0** [comment]
> Can you either remove it, or embed relevant parts? Similar to what I did with PropVar, PropertyKey and others.

I've looked at the UACHelper project, it'll be needed to rip the whole project to make it work. I don't think it would be wise. And I personally don't like to reinvent the wheel and copy-paste code from packages. However I see your point and will remove UACHelper from the code.

BTW regarding single-file idea, have you thought about moving to .NET Core? It has [a single-file publishing feature](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli).

**Comment by Jamminroot** [comment]
That's a good point to consider. 
I'll merge request as is, and will probs migrate to newer dotnet and go for single-file deployment by the weekend.

Again, thanks for you contribution, that's really appreciated 👍

**Pull request merged**
